#!/bin/zsh -feu

# Git merge with a remote, in a way that reprepro DB/ is merged too.

REMOTE=github
DISTRO=sid

while
    git fetch $REMOTE
    sha=$(git rev-parse FETCH_HEAD)
    echo "at $sha" >&2

    # I need to be sure the update is
    reprepro dumpupdate $DISTRO |grep -v "^keep"
    reprepro update $DISTRO
    # again
    git fetch $REMOTE
    new_sha=$(git rev-parse FETCH_HEAD)
    echo "at $new_sha" >&2
    # if different, repeat!
    [[ $sha != $new_sha ]]
do :; done

# now I got both reprepro & git aligned:

head=$(git rev-parse HEAD)
if [[ $sha != $head ]]
   # git status;
then
    git commit -m "reprepro update from $sha"

    git merge --no-commit $sha
    git reset dists/
    #  -s ort --strategy-option=ours
    git commit -m "update & merge to $REMOTE"
else
    echo "no update detected"
fi

# reprepro dumpunreferenced
# checkpool

./deploy

