#!/bin/zsh -feu

# checksums:
if ! reprepro checkpool;
   # Missing file ....old versions?
   # ... how to prune these files (from binary indices?)?
   #
   # There were files with only some of the checksums this version of reprepro
   # can compute recorded. To add those run reprepro collectnewchecksums.
then
    # db5.3_dump -p db/checksums.db  |grep apt-doc
    # so indeed the `missing' files are there:
    rm -f db/checksums*
    reprepro collectnewchecksums
# Warning: readded existing file 'pool/main/a/apt/apt_2.9.17-maruska_amd64.deb' mysteriously missing from the checksum database.
    reprepro checkpool;
    # but I still have apt-doc ... previous and just-built versions in pool/ but not in the checksums.db
    # why?
    # grep-dctrl -P apt-doc dists/sid/main/binary-arm64/Packages
    # shows the previous
    # ... so?
fi


# `Reprepro'
# --export=(silent-never|never|changed|lookedat|force)
# --export=changed
# --endhook hookscript
# --outhook

# export  -- generate dists/*


grep-dctrl -P git-daemon-sysvinit dists/sid/main/binary-arm64/Packages


# this only looks at db/* files?
reprepro check
# Warning: readded existing file 'pool/main/a/apt/apt-doc_3.1.15-maruska_all.deb' mysteriously missing from the checksum database.
#

cat <<EOF

newfstatat(AT_FDCWD, "/home/user/reprepro//pool/main/g/git/git-daemon-sysvinit_2.45.2-1-maruska_all.deb", {st_mode=S_IFREG|0664, st_size=1044600, ...}, 0) = 0
Deleting unexpected file '/home/user/reprepro//pool/main/g/git/git-daemon-sysvinit_2.45.2-1-maruska_all.deb'!
(not in database and wrong in pool)

 unlinkat(AT_FDCWD, "/home/user/reprepro//pool/main/g/git/git-daemon-sysvinit_2.45.2-1-maruska_all.deb", 0) = 0

Missing file pool/main/g/git/git-daemon-sysvinit_2.45.2-1-maruska_all.deb

Files are missing for 'git-daemon-sysvinit'!
openat(AT_FDCWD, "/home/user/reprepro//db/version.new", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
renameat(AT_FDCWD, "/home/user/reprepro//db/version.new", AT_FDCWD, "/home/user/reprepro//db/version") = 0
unlinkat(AT_FDCWD, "/home/user/reprepro//db/lockfile", 0) = 0
There have been errors!

EOF





# So changes on github remote,
# how to merge them with local changes?

reprepro checkupdate  sid
# complains about key....

reprepro update sid

reprepro dumpupdate sid
# predelete


reprepro   -C main removefilter sid     'Package (% git-man*)'

reprepro checkupdate sid


#
# File "pool/main/g/git/git-man_2.45.2-1-maruska_all.deb" is already registered with different checksums!


