name: Update Apt Repo
on:
  repository_dispatch:
    types: [new-deb-package]

jobs:
  reprepro:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
      - name: Install Tools
        run: |
          apt-get update
          # really curl?
          apt-get install -y reprepro git curl

          # 1. Create directory for the key
          mkdir -p -m 755 /etc/apt/keyrings

          # 2. Download the GitHub CLI signing key
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg
          chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

          # 3. Add the repository to your sources
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null

          # 4. Install the gh tool
          apt-get update
          apt-get install -y gh


      - name: Checkout Config (Main)
        uses: actions/checkout@v4
        with:
          path: main-source

      - name: Checkout Data (GH-Pages)
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: apt-data
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download New Package
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          mkdir -p incoming
          # Use the payload sent from your slave repo
          # Force gh to tell us what it's doing
          # --pattern "*.deb" \
          gh release download ${{ github.event.client_payload.version }} \
               --repo ${{ github.event.client_payload.repo }} \
               --dir ./incoming \
               --skip-existing

          # mmc: changes, .dsc
          ls -l incoming

      - name: Sanitize Reprepro
        run: |
          ldd $(which reprepro) |grep libdb
          # If the DB exists but reprepro fails to even check its version,
          # it's likely a BDB version mismatch.
          if ! reprepro -b ./apt-data dumpversion; then
          echo "Database version mismatch detected. Clearing old DB..."
          rm -rf ./apt-data/db
          fi

      - name: Run Reprepro
        run: |
          # Use config from main, but write data to apt-data folder
          reprepro -b ./apt-data \
                   --confdir ./main-source/conf \
                   includedeb sid ./incoming/*.deb

      - name: Push to GH-Pages
        working-directory: ./apt-data
        run: |
          git config --global user.name "Apt Robot"
          git config --global user.email "robot@example.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE/apt-data"

          # Add the new pool files, dists metadata, and the updated DB
          git add .
          git commit -m "Add ${{ github.event.client_payload.repo }} version ${{ github.event.client_payload.version }}"
          git push origin gh-pages
