name: Migrate from apt-storage branch

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro git

      - name: Checkout Config (Main)
        uses: actions/checkout@v4
        with:
          path: main-source

      - name: Checkout apt-storage branch
        uses: actions/checkout@v4
        with:
          ref: apt-storage
          path: apt-data

      - name: Clean up -- prune obsolete packages
        run: |
          # removeolderbinaries unstable package-name 1
          reprepro -b ./apt-data --confdir ./main-source/conf \
             deleteunreferenced
          du -sh apt-data/pool/*/* | sort -h


      - name: Create release from branch contents
        run: |
          tar czf reprepro-state.tar.gz --exclude='apt-data/.git'  apt-data/
          gh release delete reprepro-state \
          --repo ${{ github.repository }} --yes || true
          gh release create reprepro-state reprepro-state.tar.gz \
          --repo ${{ github.repository }} \
          --title "reprepro state" \
          --notes "Migrated from apt-storage branch" \
          --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
